export const TEST_ERRORS = {
  NO_EXCEPTION: '例外が発生しませんでした',
  WRONG_EXCEPTION_TYPE: '予期しない型のエラーが発生しました',
} as const;
